const IMAGE_URL="https://image.tmdb.org/t/p/w500";
const BACKDROP_URL="https://image.tmdb.org/t/p/w1280";
const PROFILE_URL="https://image.tmdb.org/t/p/w185";
const apiCache=new Map();
let heroMovies=[];let heroIndex=0;let heroTimer=null;let searchTimer=null;let isBrowseLoading=false;let waitingServiceWorker=null;let lastFocusedElement=null;
const browseFilters={genre:"",year:"",rating:"",sort:"popularity.desc",page:1,totalPages:1};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const homeView=$("#homeView"),browseView=$("#browseView"),browseMovies=$("#browseMovies"),searchInput=$("#searchInput"),searchSuggestions=$("#searchSuggestions"),movieDetail=$("#movieDetail"),detailBody=$("#detailBody");

function escapeHTML(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function shortenText(t="",n=140){return t.length>n?t.slice(0,n).trim()+"…":t;}
async function apiRequest(url,useCache=true){if(useCache&&apiCache.has(url))return apiCache.get(url);const p=fetch(url).then(r=>{if(!r.ok)throw new Error(`API 요청 실패: ${r.status}`);return r.json()});if(useCache)apiCache.set(url,p);try{return await p}catch(e){apiCache.delete(url);throw e}}
function getFavorites(){try{return JSON.parse(localStorage.getItem("movieFavorites"))||[]}catch{return[]}}
function saveFavorites(v){localStorage.setItem("movieFavorites",JSON.stringify(v))}
function isFavorite(id){return getFavorites().some(m=>m.id===id)}
function toggleFavorite(movie){let list=getFavorites();if(isFavorite(movie.id))list=list.filter(m=>m.id!==movie.id);else list.unshift({id:movie.id,title:movie.title,poster_path:movie.poster_path,release_date:movie.release_date,vote_average:movie.vote_average});saveFavorites(list);updateFavoriteButtons()}
function updateFavoriteButtons(){$$(".favorite-btn").forEach(b=>{const active=isFavorite(Number(b.dataset.id));b.classList.toggle("active",active);b.textContent=active?"♥":"♡";b.setAttribute("aria-pressed",String(active));b.setAttribute("aria-label",active?"즐겨찾기에서 제거":"즐겨찾기에 추가")})}
function posterFor(movie){return movie.poster_path?`${IMAGE_URL}${movie.poster_path}`:"/assets/images/poster-placeholder.svg"}
function createMovieCard(movie,index=0,showRank=false){const card=document.createElement("article");card.className="movie-card";card.dataset.movie=JSON.stringify({id:movie.id,title:movie.title,poster_path:movie.poster_path,release_date:movie.release_date,vote_average:movie.vote_average});const year=(movie.release_date||"").slice(0,4)||"-";card.innerHTML=`<div class="poster-wrap"><img src="${posterFor(movie)}" alt="${escapeHTML(movie.title)} 포스터" loading="lazy" decoding="async"><button class="favorite-btn" data-id="${movie.id}" type="button">♡</button><div class="movie-overlay"><div class="hover-info">${showRank?`<strong>#${index+1}</strong>`:""}<div>⭐ ${(movie.vote_average||0).toFixed(1)} · ${year}</div><button class="detail-button detail-btn" data-id="${movie.id}" type="button">상세보기</button></div></div></div><div class="movie-info"><h3 class="movie-title">${escapeHTML(movie.title||"제목 없음")}</h3><div class="movie-meta">⭐ ${(movie.vote_average||0).toFixed(1)} · ${year}</div></div>`;card.querySelector("img").addEventListener("error",e=>{if(!e.currentTarget.src.includes("poster-placeholder"))e.currentTarget.src="/assets/images/poster-placeholder.svg"});return card}
function renderMovieSection(id,movies,rank=false){const el=document.getElementById(id);if(!el)return;el.innerHTML="";(movies||[]).filter(m=>m.poster_path).slice(0,20).forEach((m,i)=>el.append(createMovieCard(m,i,rank)));updateFavoriteButtons()}
function renderBrowse(list){browseMovies.innerHTML="";(list||[]).forEach((m,i)=>browseMovies.append(createMovieCard(m,i,false)));updateFavoriteButtons()}
function appendBrowse(list){(list||[]).forEach((m,i)=>browseMovies.append(createMovieCard(m,i,false)));updateFavoriteButtons()}
function showSkeleton(id,count=8){const el=document.getElementById(id);if(!el)return;el.innerHTML=Array.from({length:count},()=>'<div class="movie-card skeleton"></div>').join("")}

async function getPopularMovies(){showSkeleton("popularMovies");const d=await apiRequest("/api/tmdb?path=popular");renderMovieSection("popularMovies",d.results,true);setupHeroSlider(d.results||[])}
async function getNowPlayingMovies(){showSkeleton("nowPlayingMovies");try{const d=await apiRequest("/api/tmdb?path=now-playing");renderMovieSection("nowPlayingMovies",d.results)}catch{$("#nowPlayingMovies").innerHTML='<p class="state-message">현재 상영작을 불러오지 못했습니다.</p>'}}
async function getUpcomingMovies(){showSkeleton("upcomingMovies");try{const d=await apiRequest("/api/tmdb?path=upcoming");renderMovieSection("upcomingMovies",d.results)}catch{$("#upcomingMovies").innerHTML='<p class="state-message">개봉 예정작을 불러오지 못했습니다.</p>'}}
async function getTopRatedMovies(){showSkeleton("topRatedMovies");try{const d=await apiRequest("/api/tmdb?path=top-rated");renderMovieSection("topRatedMovies",d.results)}catch{$("#topRatedMovies").innerHTML='<p class="state-message">평점 높은 영화를 불러오지 못했습니다.</p>'}}

function setupHeroSlider(movies){heroMovies=(movies||[]).filter(m=>m.backdrop_path&&m.overview).slice(0,5);if(!heroMovies.length)return;heroIndex=0;showHero();startHeroTimer()}
function showHero(){const m=heroMovies[heroIndex];if(!m)return;$("#heroSection").style.backgroundImage=`url(${BACKDROP_URL}${m.backdrop_path})`;$("#heroTitle").textContent=m.title;$("#heroRating").textContent=`⭐ ${(m.vote_average||0).toFixed(1)}`;$("#heroYear").textContent=(m.release_date||"").slice(0,4);$("#heroOverview").textContent=shortenText(m.overview||"줄거리 정보가 없습니다.",180);$("#heroDetailButton").dataset.id=m.id;const box=$("#heroIndicators");box.innerHTML=heroMovies.map((_,i)=>`<button class="${i===heroIndex?"active":""}" data-hero="${i}" aria-label="추천 영화 ${i+1}"></button>`).join("")}
function moveHero(dir){if(!heroMovies.length)return;heroIndex=(heroIndex+dir+heroMovies.length)%heroMovies.length;showHero();startHeroTimer()}
function startHeroTimer(){clearInterval(heroTimer);if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;heroTimer=setInterval(()=>moveHero(1),6000)}

async function searchMovies(){const q=searchInput.value.trim();if(!q)return;hideSuggestions();showView("movies");$("#browseTitle").textContent=`🔎 '${q}' 검색 결과`;$("#browseDescription").textContent="검색된 영화를 확인하세요.";browseMovies.innerHTML='<p class="state-message">검색 중...</p>';try{const d=await apiRequest(`/api/tmdb?path=search&query=${encodeURIComponent(q)}`,false);if(!d.results?.length){browseMovies.innerHTML='<p class="state-message">검색 결과가 없습니다.</p>';return}renderBrowse(d.results)}catch{browseMovies.innerHTML='<p class="state-message">검색 중 오류가 발생했습니다.</p>'}}
async function getSearchSuggestions(q){if(q.length<2){hideSuggestions();return}try{const d=await apiRequest(`/api/tmdb?path=search&query=${encodeURIComponent(q)}`,false);const list=(d.results||[]).filter(m=>m.poster_path).slice(0,6);if(!list.length){hideSuggestions();return}searchSuggestions.innerHTML=list.map(m=>`<div class="suggestion" role="option" data-id="${m.id}"><img src="${posterFor(m)}" alt=""><div><strong>${escapeHTML(m.title)}</strong><br><small>${(m.release_date||"").slice(0,4)}</small></div></div>`).join("");searchSuggestions.classList.remove("hidden");searchInput.setAttribute("aria-expanded","true")}catch{hideSuggestions()}}
function hideSuggestions(){searchSuggestions?.classList.add("hidden");searchInput?.setAttribute("aria-expanded","false")}

async function getMovieDetail(id,updateUrl=true){lastFocusedElement=document.activeElement;try{const m=await apiRequest(`/api/tmdb?path=detail&id=${id}`);renderDetail(m);movieDetail.classList.remove("hidden");document.body.style.overflow="hidden";$("#detailClose").focus();if(updateUrl){const u=new URL(location.href);u.searchParams.set("movie",id);history.pushState({movieId:id},"",u)}updateSEO(m)}catch{detailBody.innerHTML='<div class="state-message"><h2>영화를 불러올 수 없습니다.</h2><p>잠시 후 다시 시도해주세요.</p></div>';movieDetail.classList.remove("hidden")}}
function renderDetail(m){const director=m.credits?.crew?.find(x=>x.job==="Director")?.name||"정보 없음";const cast=(m.credits?.cast||[]).slice(0,6);const trailer=(m.videos?.results||[]).find(v=>v.site==="YouTube"&&v.type==="Trailer");const genres=(m.genres||[]).map(g=>`<span class="tag">${escapeHTML(g.name)}</span>`).join("");detailBody.innerHTML=`<div class="detail-hero" style="background-image:url('${m.backdrop_path?BACKDROP_URL+m.backdrop_path:""}')"><div class="detail-main"><img class="detail-poster" src="${posterFor(m)}" alt="${escapeHTML(m.title)} 포스터"><div class="detail-copy"><h1 id="detailTitle">${escapeHTML(m.title)}</h1><div class="detail-tags">${genres}</div><p>⭐ ${(m.vote_average||0).toFixed(1)} · ${(m.release_date||"").slice(0,4)} · ${m.runtime||"-"}분</p><p>${escapeHTML(m.overview||"줄거리 정보가 없습니다.")}</p><p><strong>감독:</strong> ${escapeHTML(director)}</p><button class="secondary-button" id="shareMovieButton" type="button">공유하기</button></div></div></div><section class="detail-section"><h2>출연진</h2><div class="cast-grid">${cast.map(c=>`<div class="cast-card"><img src="${c.profile_path?PROFILE_URL+c.profile_path:"/assets/images/poster-placeholder.svg"}" alt="${escapeHTML(c.name)}" loading="lazy"><div class="cast-info"><strong>${escapeHTML(c.name)}</strong><span>${escapeHTML(c.character||"")}</span></div></div>`).join("")}</div></section>${trailer?`<section class="detail-section"><h2>예고편</h2><div class="trailer-wrap"><iframe src="https://www.youtube.com/embed/${encodeURIComponent(trailer.key)}" title="${escapeHTML(m.title)} 예고편" loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div></section>`:""}<section class="detail-section"><h2>이 영화를 좋아한다면</h2><div class="movie-row" id="similarMovies"></div></section>`;renderMovieSection("similarMovies",m.similar?.results||[])}
function closeMovieDetail(){movieDetail.classList.add("hidden");document.body.style.overflow="";const u=new URL(location.href);u.searchParams.delete("movie");history.pushState({},"",u);resetSEO();lastFocusedElement?.focus?.()}
function updateSEO(m){document.title=`${m.title} | MOVIEBOX`;const desc=shortenText(m.overview||"MOVIEBOX 영화 상세정보",150);document.querySelector('meta[name="description"]').content=desc;$("#ogTitle").content=m.title;$("#ogDescription").content=desc;$("#ogImage").content=m.backdrop_path?BACKDROP_URL+m.backdrop_path:posterFor(m);$("#ogUrl").content=location.href}
function resetSEO(){document.title="MOVIEBOX - 영화 정보 서비스";$("#ogUrl").content=location.origin}
function handleMovieUrl(){const id=new URL(location.href).searchParams.get("movie");if(id)getMovieDetail(id,false)}

function createYearOptions(){const y=$("#filterYear");for(let n=new Date().getFullYear();n>=1980;n--){const o=document.createElement("option");o.value=n;o.textContent=`${n}년`;y.append(o)}}
async function loadBrowseMovies(){if(isBrowseLoading||browseFilters.page>browseFilters.totalPages)return;isBrowseLoading=true;const p=new URLSearchParams({path:"discover",page:String(browseFilters.page),sort:browseFilters.sort});if(browseFilters.genre)p.set("genre",browseFilters.genre);if(browseFilters.year)p.set("year",browseFilters.year);if(browseFilters.rating)p.set("rating",browseFilters.rating);try{const d=await apiRequest(`/api/tmdb?${p}`);browseFilters.totalPages=Math.min(d.total_pages||1,500);browseFilters.page===1?renderBrowse(d.results):appendBrowse(d.results)}catch{if(browseFilters.page===1)browseMovies.innerHTML='<p class="state-message">영화를 불러오지 못했습니다.</p>';else browseFilters.page--}finally{isBrowseLoading=false}}
function reloadBrowse(){browseFilters.page=1;browseFilters.totalPages=1;loadBrowseMovies()}
function showView(name){homeView.classList.toggle("hidden",name!=="home");browseView.classList.toggle("hidden",name==="home");$$('.nav-link').forEach(a=>a.classList.toggle("active",a.dataset.view===name));if(name==="movies"){$("#browseTitle").textContent="🎬 영화 탐색";$("#browseDescription").textContent="필터로 원하는 영화를 찾아보세요.";reloadBrowse()}if(name==="popular"){$("#browseTitle").textContent="🔥 인기 영화";$("#browseDescription").textContent="현재 인기 있는 영화입니다.";apiRequest("/api/tmdb?path=popular").then(d=>renderBrowse(d.results))}if(name==="favorites"){$("#browseTitle").textContent="♥ 즐겨찾기";$("#browseDescription").textContent="저장한 영화입니다.";const f=getFavorites();f.length?renderBrowse(f):browseMovies.innerHTML='<p class="state-message">저장한 영화가 없습니다.</p>'}}

const observer=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting||browseView.classList.contains("hidden")||isBrowseLoading||browseFilters.page>=browseFilters.totalPages)return;browseFilters.page++;loadBrowseMovies()},{rootMargin:"500px 0px"});observer.observe($("#infiniteScrollTrigger"));

document.addEventListener("click",e=>{const d=e.target.closest(".detail-btn");if(d)return getMovieDetail(d.dataset.id);const f=e.target.closest(".favorite-btn");if(f){const card=f.closest(".movie-card");return toggleFavorite(JSON.parse(card.dataset.movie))}const s=e.target.closest(".slider-btn");if(s){const c=document.getElementById(s.dataset.target);c?.scrollBy({left:(s.classList.contains("slider-next")?1:-1)*c.clientWidth*.8,behavior:"smooth"});return}const nav=e.target.closest("[data-view]");if(nav){e.preventDefault();showView(nav.dataset.view);return}const foot=e.target.closest("[data-footer-view]");if(foot){e.preventDefault();showView(foot.dataset.footerView);scrollTo({top:0,behavior:"smooth"});return}const sug=e.target.closest(".suggestion");if(sug){hideSuggestions();getMovieDetail(sug.dataset.id);return}const hi=e.target.closest("[data-hero]");if(hi){heroIndex=Number(hi.dataset.hero);showHero();startHeroTimer()}if(!e.target.closest(".search-box-wrap"))hideSuggestions()});
$("#searchButton").addEventListener("click",searchMovies);searchInput.addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>getSearchSuggestions(searchInput.value.trim()),350)});searchInput.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();searchMovies()}});$("#heroPrev").addEventListener("click",()=>moveHero(-1));$("#heroNext").addEventListener("click",()=>moveHero(1));$("#heroDetailButton").addEventListener("click",e=>getMovieDetail(e.currentTarget.dataset.id));$("#heroMovieButton").addEventListener("click",()=>showView("popular"));$("#logoButton").addEventListener("click",()=>showView("home"));$("#detailClose").addEventListener("click",closeMovieDetail);
$("#filterGenre").addEventListener("change",e=>{browseFilters.genre=e.target.value;reloadBrowse()});$("#filterYear").addEventListener("change",e=>{browseFilters.year=e.target.value;reloadBrowse()});$("#filterRating").addEventListener("change",e=>{browseFilters.rating=e.target.value;reloadBrowse()});$("#filterSort").addEventListener("change",e=>{browseFilters.sort=e.target.value;reloadBrowse()});$("#filterReset").addEventListener("click",()=>{$("#filterGenre").value="";$("#filterYear").value="";$("#filterRating").value="";$("#filterSort").value="popularity.desc";Object.assign(browseFilters,{genre:"",year:"",rating:"",sort:"popularity.desc",page:1,totalPages:1});loadBrowseMovies()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(!movieDetail.classList.contains("hidden"))closeMovieDetail();hideSuggestions()}});window.addEventListener("popstate",handleMovieUrl);window.addEventListener("offline",()=>$("#networkBanner").classList.remove("hidden"));window.addEventListener("online",()=>$("#networkBanner").classList.add("hidden"));

detailBody.addEventListener("click",async e=>{if(e.target.id!=="shareMovieButton")return;try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);alert("주소를 복사했습니다.")}}catch{}});
function hideLoader(){$("#appLoader").classList.add("hidden");setTimeout(()=>$("#appLoader")?.remove(),300)}
async function registerServiceWorker(){if(!("serviceWorker" in navigator))return;try{const r=await navigator.serviceWorker.register("/sw.js");if(r.waiting){waitingServiceWorker=r.waiting;$("#updateToast").classList.remove("hidden")}r.addEventListener("updatefound",()=>{const w=r.installing;w?.addEventListener("statechange",()=>{if(w.state==="installed"&&navigator.serviceWorker.controller){waitingServiceWorker=w;$("#updateToast").classList.remove("hidden")}})})}catch(e){console.error("Service Worker 등록 실패",e)}}
$("#updateAppButton").addEventListener("click",()=>waitingServiceWorker?.postMessage({type:"SKIP_WAITING"}));let refreshing=false;navigator.serviceWorker?.addEventListener("controllerchange",()=>{if(refreshing)return;refreshing=true;location.reload()});
async function startApp(){createYearOptions();$("#footerYear").textContent=new Date().getFullYear();try{await getPopularMovies()}catch(e){console.error(e);$("#popularMovies").innerHTML='<p class="state-message">인기 영화를 불러오지 못했습니다.</p>'}finally{hideLoader()}Promise.allSettled([getNowPlayingMovies(),getUpcomingMovies(),getTopRatedMovies()]);handleMovieUrl();registerServiceWorker()}
startApp();
