/* MOVIEBOX enhancement bundle: favorites, recent search, trailer, details, crew, recommendations, history */

(()=>{
  const STORAGE_KEY="movieFavorites";
  const detailBody=document.querySelector("#detailBody");
  if(!detailBody)return;
  function getFavorites(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{return[]}}
  function saveFavorites(list){localStorage.setItem(STORAGE_KEY,JSON.stringify(list))}
  function getMovieId(){const id=new URL(location.href).searchParams.get("movie");return /^\d+$/.test(id||"")?Number(id):null}
  function isFavorite(id){return getFavorites().some(movie=>Number(movie.id)===Number(id))}
  function syncCardButtons(id){const active=isFavorite(id);document.querySelectorAll(`.favorite-btn[data-id="${id}"]`).forEach(button=>{button.classList.toggle("active",active);button.textContent=active?"♥":"♡";button.setAttribute("aria-pressed",String(active));button.setAttribute("aria-label",active?"즐겨찾기에서 제거":"즐겨찾기에 추가")})}
  function updateDetailButton(button,id){const active=isFavorite(id);button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));button.innerHTML=active?"<span>♥</span> 즐겨찾기 저장됨":"<span>♡</span> 즐겨찾기 추가"}
  async function toggleDetailFavorite(button,id){button.disabled=true;try{let list=getFavorites();if(isFavorite(id)){list=list.filter(movie=>Number(movie.id)!==Number(id))}else{const response=await fetch(`/api/tmdb?path=detail&id=${id}`);if(!response.ok)throw new Error("영화 정보를 불러오지 못했습니다.");const movie=await response.json();list.unshift({id:movie.id,title:movie.title,poster_path:movie.poster_path,release_date:movie.release_date,vote_average:movie.vote_average})}saveFavorites(list);updateDetailButton(button,id);syncCardButtons(id)}catch(error){console.error(error);button.textContent="다시 시도해주세요";setTimeout(()=>updateDetailButton(button,id),1200)}finally{button.disabled=false}}
  function enhanceDetail(){const id=getMovieId();const shareButton=detailBody.querySelector("#shareMovieButton");if(!id||!shareButton||detailBody.querySelector("#detailFavoriteButton"))return;let actions=shareButton.closest(".detail-actions");if(!actions){actions=document.createElement("div");actions.className="detail-actions";shareButton.parentNode.insertBefore(actions,shareButton);actions.appendChild(shareButton)}const button=document.createElement("button");button.id="detailFavoriteButton";button.className="detail-favorite-button";button.type="button";button.dataset.id=String(id);updateDetailButton(button,id);button.addEventListener("click",()=>toggleDetailFavorite(button,id));actions.insertBefore(button,shareButton)}
  new MutationObserver(enhanceDetail).observe(detailBody,{childList:true,subtree:true});window.addEventListener("popstate",()=>setTimeout(enhanceDetail,0));enhanceDetail();
})();

(()=>{
  const STORAGE_KEY="movieRecentSearches";const input=document.querySelector("#searchInput");const button=document.querySelector("#searchButton");const panel=document.querySelector("#searchSuggestions");if(!input||!button||!panel)return;
  function getRecent(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{return[]}}
  function saveRecent(query){const q=String(query||"").trim();if(!q)return;const next=[q,...getRecent().filter(x=>x!==q)].slice(0,6);localStorage.setItem(STORAGE_KEY,JSON.stringify(next))}
  function removeRecent(query){localStorage.setItem(STORAGE_KEY,JSON.stringify(getRecent().filter(x=>x!==query)));showRecent()}
  function clearRecent(){localStorage.removeItem(STORAGE_KEY);showRecent()}
  function runRecentSearch(query){input.value=query;saveRecent(query);panel.classList.add("hidden");input.setAttribute("aria-expanded","false");button.click()}
  function escapeHTML(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
  function showRecent(){if(input.value.trim())return;const recent=getRecent();if(!recent.length){panel.classList.add("hidden");input.setAttribute("aria-expanded","false");return}panel.innerHTML=`<div class="recent-search-head"><strong>최근 검색어</strong><button type="button" class="recent-clear">전체 삭제</button></div><div class="recent-search-list">${recent.map(q=>`<div class="recent-search-item"><button type="button" class="recent-query" data-query="${escapeHTML(q)}"><span>🕘</span><span>${escapeHTML(q)}</span></button><button type="button" class="recent-remove" data-remove="${escapeHTML(q)}" aria-label="${escapeHTML(q)} 삭제">×</button></div>`).join("")}</div>`;panel.classList.remove("hidden");input.setAttribute("aria-expanded","true")}
  button.addEventListener("click",()=>saveRecent(input.value));input.addEventListener("keydown",e=>{if(e.key==="Enter")saveRecent(input.value)});input.addEventListener("focus",()=>{if(!input.value.trim())showRecent()});input.addEventListener("input",()=>{if(!input.value.trim())setTimeout(showRecent,0)});
  panel.addEventListener("click",e=>{const recentBtn=e.target.closest(".recent-query");if(recentBtn){e.preventDefault();e.stopPropagation();runRecentSearch(recentBtn.dataset.query);return}const removeBtn=e.target.closest(".recent-remove");if(removeBtn){e.preventDefault();e.stopPropagation();removeRecent(removeBtn.dataset.remove);return}if(e.target.closest(".recent-clear")){e.preventDefault();e.stopPropagation();clearRecent()}});
  const results=document.querySelector("#browseMovies");const title=document.querySelector("#browseTitle");if(results&&title){const observer=new MutationObserver(()=>{if(!title.textContent.includes("검색 결과"))return;const count=results.querySelectorAll(".movie-card").length;const desc=document.querySelector("#browseDescription");if(desc&&count)desc.textContent=`검색 결과 ${count}개를 먼저 보여드리고 있습니다.`});observer.observe(results,{childList:true})}
})();

(()=>{
  const detailBody=document.querySelector('#detailBody');if(!detailBody)return;
  function enhanceTrailer(){const iframe=detailBody.querySelector('.trailer-wrap iframe');const copy=detailBody.querySelector('.detail-copy');if(!copy)return;const oldButton=copy.querySelector('#detailTrailerButton');if(!iframe){oldButton?.remove();return}const trailerSection=iframe.closest('.detail-section');if(trailerSection&&!trailerSection.id)trailerSection.id='movieTrailerSection';if(!copy.querySelector('#detailTrailerButton')){const actions=copy.querySelector('.detail-actions')||copy;const button=document.createElement('button');button.id='detailTrailerButton';button.className='detail-trailer-button';button.type='button';button.innerHTML='<span aria-hidden="true">▶</span> 예고편 보기';button.addEventListener('click',()=>{trailerSection?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>iframe.focus({preventScroll:true}),450)});actions.appendChild(button)}const src=iframe.getAttribute('src')||'';if(src&&!src.includes('rel=0')){const separator=src.includes('?')?'&':'?';iframe.setAttribute('src',`${src}${separator}rel=0&modestbranding=1`)}iframe.setAttribute('allow','accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share')}
  const observer=new MutationObserver(()=>enhanceTrailer());observer.observe(detailBody,{childList:true,subtree:true});enhanceTrailer();
})();

(()=>{
  const esc=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const formatDate=value=>{if(!value)return "정보 없음";const d=new Date(value);if(Number.isNaN(d.getTime()))return esc(value);return new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric"}).format(d)};
  const getCertification=movie=>{const groups=movie.release_dates?.results||[];const kr=groups.find(x=>x.iso_3166_1==="KR");const fallback=groups.find(x=>x.iso_3166_1==="US")||groups[0];const pick=group=>(group?.release_dates||[]).find(x=>String(x.certification||"").trim())?.certification||"";const cert=pick(kr)||pick(fallback);if(!cert)return "정보 없음";const map={"ALL":"전체 관람가","12":"12세 이상 관람가","15":"15세 이상 관람가","18":"청소년 관람불가","R":"R","PG":"PG","PG-13":"PG-13","G":"G","NC-17":"NC-17"};return map[cert]||cert};
  const renderInfo=movie=>{const detail=document.querySelector("#detailBody");if(!detail||detail.querySelector(".extended-info"))return;const firstSection=detail.querySelector(".detail-section");if(!firstSection)return;const countries=(movie.production_countries||[]).map(x=>x.name).filter(Boolean);const companies=(movie.production_companies||[]).map(x=>x.name).filter(Boolean).slice(0,4);const originalTitle=movie.original_title&&movie.original_title!==movie.title?movie.original_title:"-";const statusMap={Released:"개봉",Post_Production:"후반 작업",In_Production:"제작 중",Planned:"기획",Canceled:"취소",Rumored:"검토 중"};const section=document.createElement("section");section.className="detail-section extended-info";section.innerHTML=`<h2>영화 정보</h2><div class="movie-facts"><div class="movie-fact"><span>개봉일</span><strong>${formatDate(movie.release_date)}</strong></div><div class="movie-fact"><span>관람등급</span><strong>${esc(getCertification(movie))}</strong></div><div class="movie-fact"><span>제작 국가</span><strong>${esc(countries.join(", ")||"정보 없음")}</strong></div><div class="movie-fact"><span>제작사</span><strong>${esc(companies.join(", ")||"정보 없음")}</strong></div><div class="movie-fact"><span>원제</span><strong>${esc(originalTitle)}</strong></div><div class="movie-fact"><span>상태</span><strong>${esc(statusMap[movie.status]||movie.status||"정보 없음")}</strong></div></div>`;firstSection.before(section)};
  const originalFetch=window.fetch;window.fetch=async(...args)=>{const response=await originalFetch(...args);try{const url=String(args[0] instanceof Request?args[0].url:args[0]);if(url.includes("/api/tmdb?path=detail")){response.clone().json().then(data=>{if(data?.id)setTimeout(()=>renderInfo(data),0)}).catch(()=>{})}}catch{}return response};
})();

(()=>{
  const detailBody=document.getElementById("detailBody");if(!detailBody)return;const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const uniqByName=list=>{const seen=new Set();return list.filter(item=>{const key=`${item.name}|${item.job||item.character||""}`;if(seen.has(key))return false;seen.add(key);return true})};
  function movieIdFromLocation(){return new URL(location.href).searchParams.get("movie")}
  function personCard(person,role){const image=person.profile_path?`https://image.tmdb.org/t/p/w185${person.profile_path}`:"/assets/images/poster-placeholder.svg";return `<article class="person-detail-card"><img src="${image}" alt="${esc(person.name)}" loading="lazy"><div><strong>${esc(person.name)}</strong><span>${esc(role||"")}</span></div></article>`}
  function crewLine(label,people){const names=uniqByName(people).slice(0,5).map(p=>esc(p.name)).join(", ");if(!names)return "";return `<div class="crew-summary-row"><span>${label}</span><strong>${names}</strong></div>`}
  async function enhance(){const id=movieIdFromLocation();if(!id||detailBody.querySelector("[data-crew-enhanced]"))return;try{const response=await fetch(`/api/tmdb?path=detail&id=${encodeURIComponent(id)}`);if(!response.ok)return;const movie=await response.json();const crew=movie.credits?.crew||[];const cast=movie.credits?.cast||[];const directors=crew.filter(p=>p.job==="Director");const writers=crew.filter(p=>["Screenplay","Writer","Story"].includes(p.job));const producers=crew.filter(p=>["Producer","Executive Producer"].includes(p.job));const keyCrew=uniqByName([...directors,...writers,...producers]).slice(0,8);const mainCast=cast.slice(0,10);const infoSection=detailBody.querySelector(".detail-info-section");const castSection=[...detailBody.querySelectorAll(".detail-section")].find(s=>s.querySelector("h2")?.textContent?.includes("출연진"));const anchor=infoSection||castSection||detailBody.lastElementChild;const section=document.createElement("section");section.className="detail-section crew-detail-section";section.dataset.crewEnhanced="true";section.innerHTML=`<h2>🎬 주요 제작진</h2><div class="crew-summary">${crewLine("감독",directors)}${crewLine("각본",writers)}${crewLine("제작",producers)}</div>${keyCrew.length?`<div class="person-detail-grid crew-person-grid">${keyCrew.map(p=>personCard(p,p.job)).join("")}</div>`:""}<div class="cast-role-heading"><h3>주요 배우와 배역</h3><span>${mainCast.length?`${mainCast.length}명`:"정보 없음"}</span></div>${mainCast.length?`<div class="person-detail-grid">${mainCast.map(p=>personCard(p,p.character||"배역 정보 없음")).join("")}</div>`:'<p class="crew-empty">배우 정보가 없습니다.</p>'}`;if(anchor?.parentNode)anchor.parentNode.insertBefore(section,anchor.nextSibling);else detailBody.appendChild(section)}catch(error){console.warn("제작진 정보 강화 실패",error)}}
  const observer=new MutationObserver(()=>{if(!document.getElementById("movieDetail")?.classList.contains("hidden")&&detailBody.querySelector("#detailTitle")){enhance()}});observer.observe(detailBody,{childList:true,subtree:true});window.addEventListener("popstate",()=>setTimeout(enhance,100));
})();

(function(){
  const detailBody=document.querySelector('#detailBody');if(!detailBody)return;const observer=new MutationObserver(()=>{const similar=document.querySelector('#similarMovies');if(!similar||document.querySelector('#recommendedMovies'))return;const movieId=new URL(location.href).searchParams.get('movie');if(!movieId)return;fetch(`/api/tmdb?path=detail&id=${encodeURIComponent(movieId)}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{const list=(data.recommendations?.results||[]).filter(m=>m.poster_path).slice(0,20);if(!list.length)return;const section=document.createElement('section');section.className='detail-section recommendation-section';section.innerHTML='<div class="recommendation-heading"><div><span class="recommendation-kicker">MOVIEBOX PICK</span><h2>이 영화 다음엔?</h2><p>TMDB 추천 데이터를 바탕으로 이어서 보기 좋은 작품입니다.</p></div></div><div class="movie-row" id="recommendedMovies"></div>';similar.closest('.detail-section')?.after(section);if(typeof window.renderMovieSection==='function'){window.renderMovieSection('recommendedMovies',list)}else{const row=section.querySelector('#recommendedMovies');list.forEach(m=>{const card=document.createElement('button');card.className='recommendation-card';card.type='button';card.dataset.id=m.id;card.innerHTML=`<img src="https://image.tmdb.org/t/p/w500${m.poster_path}" alt="${(m.title||'영화').replace(/"/g,'&quot;')} 포스터"><span>${m.title||'제목 없음'}</span>`;row.append(card)})}}).catch(()=>{})});observer.observe(detailBody,{childList:true,subtree:true});document.addEventListener('click',e=>{const card=e.target.closest('.recommendation-card');if(!card)return;if(typeof window.getMovieDetail==='function')window.getMovieDetail(card.dataset.id)})
})();

(function(){
  const detail=document.querySelector('#movieDetail');if(!detail)return;function movieIdFromUrl(){return new URL(location.href).searchParams.get('movie')}function closeDetailWithoutHistory(){detail.classList.add('hidden');document.body.style.overflow='';document.title='MOVIEBOX - 영화 정보 서비스';const ogUrl=document.querySelector('#ogUrl');if(ogUrl)ogUrl.content=location.origin}window.addEventListener('popstate',()=>{if(!movieIdFromUrl()&&!detail.classList.contains('hidden'))closeDetailWithoutHistory()});document.addEventListener('click',event=>{if(!event.target.closest('#detailClose'))return;if(movieIdFromUrl()&&history.state?.movieId){event.preventDefault();event.stopImmediatePropagation();history.back()}},true);document.addEventListener('keydown',event=>{if(event.key!=='Escape'||detail.classList.contains('hidden'))return;if(movieIdFromUrl()&&history.state?.movieId){event.preventDefault();event.stopImmediatePropagation();history.back()}},true)
})();
