const CACHE_NAME="moviebox-v3";
const APP_SHELL=["/","/index.html","/offline.html","/css/style.css","/js/app.js","/manifest.webmanifest","/assets/icons/favicon.svg","/assets/icons/icon-192.svg","/assets/icons/icon-512.svg","/assets/images/poster-placeholder.svg"];
self.addEventListener("install",event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(APP_SHELL)));});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));self.clients.claim();});
self.addEventListener("message",event=>{if(event.data?.type==="SKIP_WAITING")self.skipWaiting();});
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(request.mode==="navigate"){event.respondWith(handleNavigation(request));return;}if(url.pathname.startsWith("/api/")){event.respondWith(networkFirst(request));return;}if(url.hostname==="image.tmdb.org"){event.respondWith(cacheFirst(request));return;}event.respondWith(staleWhileRevalidate(request));});
async function handleNavigation(request){try{return await fetch(request)}catch{const cached=await caches.match(request);return cached||caches.match("/offline.html")}}
async function networkFirst(request){try{const response=await fetch(request);if(response.ok){const cache=await caches.open(CACHE_NAME);cache.put(request,response.clone())}return response}catch{const cached=await caches.match(request);return cached||new Response(JSON.stringify({error:"현재 오프라인 상태입니다."}),{status:503,headers:{"Content-Type":"application/json"}})}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;try{const response=await fetch(request);if(response.ok){const cache=await caches.open(CACHE_NAME);cache.put(request,response.clone())}return response}catch{return new Response("",{status:503,statusText:"Offline"})}}
async function staleWhileRevalidate(request){const cache=await caches.open(CACHE_NAME);const cached=await cache.match(request);const network=fetch(request).then(response=>{if(response.ok)cache.put(request,response.clone());return response}).catch(()=>null);return cached||network||new Response("Offline",{status:503})}
